# grpc address
# grpc_addr = "http://0.0.0.0:9090"
grpc_addr = "http://10.176.35.58:9090"
# tendermint rpc address
tendermint_rpc_addr = "http://10.176.35.58:26657"
# blockchain API
blockchain_api_addr = "http://10.176.35.58:1317"
# [execution]
# performance_duration = 15000
# performance_internal = 2000
# crash_duration = 30000
# malicious_duration = 20000