chain_id = "test_chain"
# grpc address
# grpc_addr = "http://0.0.0.0:9090"
grpc_addr = "http://10.176.35.58:9090"
# tendermint rpc address
tendermint_rpc_addr = "http://10.176.35.58:26657"
# blockchain API
blockchain_api_addr = "http://10.176.35.58:1317"
# [execution]
# performance_duration = 15000
# performance_internal = 2000
# crash_duration = 30000
# malicious_duration = 20000
chain_a_key_path = "/Users/joten/rust_projects/TxAggregator/cosmos_chain/src/config/key_a.toml"
chain_b_key_path = "/Users/joten/rust_projects/TxAggregator/cosmos_chain/src/config/key_a.toml"

hd_path = "m/44'/118'/0'/0/0"

default_gas = 100
max_gas = 100
gas_multiplier = 100.0
fee_granter = "test"

[gas_price]
price = 100.0
denom = "test_denom"