chain_id = "test_chain"
# grpc address
grpc_addr = "http://0.0.0.0:9090"
# grpc_addr = "http://10.176.35.58:9090"
# tendermint rpc address
tendermint_rpc_addr = "http://0.0.0.0:26657"
# tendermint_rpc_addr = "http://10.176.35.58:26657"
# blockchain API
blockchain_api_addr = "http://0.0.0.0:1317"
# blockchain_api_addr = "http://10.176.35.58:1317"

# Set rpc timeout (s)
rpc_timeout = 10
# [execution]
# performance_duration = 15000
# performance_internal = 2000
# crash_duration = 30000
# malicious_duration = 20000
chain_a_key_path = "/Users/joten/rust_projects/TxAggregator/cosmos_chain/src/config/key_a.toml"
chain_b_key_path = "/Users/joten/rust_projects/TxAggregator/cosmos_chain/src/config/key_a.toml"

hd_path = "m/44'/118'/0'/0/0"

trusted_node = false

default_gas = 100000
max_gas = 400000
gas_multiplier = 1.1
fee_granter = ""

memo_prefix = ""

# Set clock dirft time (s)
clock_drift = 5
max_block_time = 30

# Set trusting period time (day)
trusting_period = 14

[trust_threshold]
numerator = 1
denominator = 3

[gas_price]
price = 0.001
denom = "stake"