name = "wjt"
type = "local"
address = "cosmos1wm7r9yfhly2df62aq2sey5lunp0775eqe63rzq"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"AkKfvRdzO+2cQt5gPaT3XDjv+W0hVwUmdD+NjotdbaJn\"}"
mnemonic = "miracle ozone wealth follow ticket twelve anger pull course trend woman comfort also basket marine normal swamp unveil naive lawn glad regret employ danger"