name = "wjt"
type = "local"
address = "cosmos16k9nuphq4xqwf23nnns3zr0fqy5f5p0vpphh7z"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"Aiq6USKewhxknjIvQLu8w3GOtitmg892m4GS86N0p42t\"}"
mnemonic = "imitate mask mask friend claim possible size multiply excuse crack cry repair audit lion hybrid organ discover resource sun split garment faint like glow"