name = "wjt"
type = "local"
address = "cosmos190fqj82k5wh7skv29p6vcxfmtqydqmnw65fk0j"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"A6F8v9eKWlTwMlXMkOwDVSGC9S2O9wu4LQIP1Faxu0kp\"}"
mnemonic = "grief infant bone zone seven glimpse rhythm concert bless rain pig patrol supply fold ketchup blood change bronze undo easy aerobic suit gossip ability"