name = "wjt"
type = "local"
# address = "cosmos1qjxsp8m9lp6q5xdzcqkvx4rmfj3qe4pyk2few7"
# pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"A2SZquqS95z2n5606hioCUUUYIJxhY4AHloIVHvuVYEj\"}"
# mnemonic = "hazard wolf pill smoke daughter update envelope furnace gasp room album foot eternal gown accuse lake glue ask bless scan pet stomach enemy design"
address = "cosmos1kntwl9s7s9aaeum5qyde9h93zdgp4nzmkekp2p"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"A+09ETh6WMc8JqQNJs+OhiMx3YbOiDYsuTUDoCirdOjg\"}"
mnemonic = "copy element twelve common undo spread scrap west defense square damp pen cricket input height alter entry bamboo leave barrel giggle resemble rescue fresh"