name = "wjt"
type = "local"
address = "cosmos1s6yr9p46fkp495t7df7qsvcux6wkd6earrj9cq"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"A9zCnVEMia9qYENbTsYEEvmbB5xYceshfXEKALFyHmyw\"}"
mnemonic = "ritual shield put wagon sea obscure zero magnet stock other game path winner plastic student palm ski keen issue joke test fold girl only"