name = "test_key"
type = "local"
address = "cosmos14hl5f9xfg6u90lwsqqz56mz3cjq2d7svmy0ffs"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"AnWi6I8CrOIAS9ee4gsjvBxXwrkEYwUykjoiTrsU5ypg\"}"
mnemonic = "rabbit police myself february rhythm whip coral pluck relief elite debris foam much ski champion scare medal walnut museum parade way field glad deal"