name = "wjt"
type = "local"
address = "cosmos1lh2t9ealucm9hlf58v4ep9xcxma9a5629ulx7j"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"AzSrgwQQeMzCk+zvBmu9pszN/FqDgb2T96FoMb08BL7t\"}"
mnemonic = "type tornado current sister april someone cook hurry garage vicious muffin gravity sense various energy hen reward catch such song mutual wool village inhale"