name = "wjt"
type = "local"
address = "cosmos1ugksl34fc63kcqhqhgpzpl4je48sa97zffdfqk"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"An5SAJLgJeskPXmbDUmHkdin/J201f8RvrSb0B/qQls2\"}"
mnemonic = "busy sentence escape exclude wheel shuffle soap puzzle involve victory phrase budget acquire umbrella stand sheriff album assist pistol lonely tonight public length narrow"