# name = "wjt"
# type = "local"
# address = "cosmos1ugksl34fc63kcqhqhgpzpl4je48sa97zffdfqk"
# pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"An5SAJLgJeskPXmbDUmHkdin/J201f8RvrSb0B/qQls2\"}"
# mnemonic = "busy sentence escape exclude wheel shuffle soap puzzle involve victory phrase budget acquire umbrella stand sheriff album assist pistol lonely tonight public length narrow"
name = "hl"
type = "local"
address = "cosmos1ddxt9pl8u3rhccay3228hvsnursj3w79lz82fu"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"A5dYPHv5J8bVAgTsyiGCsFihQkKZ2QRIJr9sberKHylj\"}"
mnemonic = "census gauge security curve hire thumb stamp about before bird media true struggle decide carbon spoon spike egg arm toe finish stem deer plastic"
