name = "wjt"
type = "local"
address = "cosmos10m02a2ypdd0a3hm506qdhgg8zcl67d6ugnvhd5"
pubkey = "{\"@type\":\"/cosmos.crypto.secp256k1.PubKey\",\"key\":\"AmkqMDscPLW8XkHx9aJ5GmDRAQ9SvwGESt8LV+0Kw10p\"}"
mnemonic = "future grass october when diamond blame please mass toddler mandate coast away conduct setup update fortune gun frown boat margin siege turkey unlock media"